name: "Angular Workflow: Build, Test, Publish"

on: [ push, pull_request ]

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         -  uses: actions/checkout@v4

         -  name: Setup Node.js
            uses: actions/setup-node@v3
            with:
               node-version: 'lts/*'
               registry-url: 'https://registry.npmjs.org'

         -  name: Print Firefox version
            run: firefox --version

         -  name: Install dependencies
            run: npm ci

         -  name: Build
            run: npm run build:demo

         -  name: Test with FirefoxHeadless
            run: npm run test:ci

         -  name: Commit new docs
            if: github.ref == 'refs/heads/develop'
            run: |
               git config --local user.email "action@github.com"
               git config --local user.name "GitHub Action"
               git add .
               git diff-index --quiet HEAD || git commit -m "[ci] Automatically built demo" || exit 0
               git push

#         -  name: Publish npm package
#            if: github.ref == 'refs/heads/main'
#            run: npm run publish
#            env:
#               NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
